### ISSUE TITLE
Metadata file

### ISSUE THREAD

**Issue by srinivasn1** [thanhhungqb/pyramid-super-resolution#2]
Could you share a copy of the metadata file created for Raf-db dataset?
Or provide more details on column 5 i.e. is_test. Is this value set to False for all images?

**Comment by thanhhungqb** [comment]
I included the sample from RAF-DB metadata.
Emotion, emotion_name, and bb column come from RAF-DB (bb are store in the text files, just read and make CSV like that).
is_test column is a flag to filter train and test inside our code, set FALSE for train and TRUE for the test set.
5_fold column is a random number from 1-5 to make sure our experiment can be reproducible later (using to separated train/validation).



![image](https://user-images.githubusercontent.com/7751531/110431902-beb5ef00-80f1-11eb-9bb6-eab7de452ed7.png)
