### ISSUE TITLE
Face Error 

### ISSUE THREAD

**Issue by WalaaFarouk31** [thanhhungqb/pyramid-super-resolution#5]
Please I got the below error when running on colab the line : python -m prlab.cli k_fold --json_conf config/raf-db.json , I downgraded fast ai and pytorch version and still not working please advise.
Error:
File "<ipython-input-4-a2e60d474a39>", line 1
    python -m prlab.cli k_fold --json_conf config/raf-db.json
                  ^
SyntaxError: invalid syntax

**Comment by thanhhungqb** [comment]
If you run on Colab, please add "!" if you run command, because mostly you are in Python code cell.
Then, it should be:
!python -m prlab.cli k_fold --json_conf config/raf-db.json
